### ISSUE TITLE
How to deal with WebSocket stream.binance.com session duration limit (24h)

### ISSUE THREAD

**Issue by denis-itskovich** [binance-exchange/binance-java-api#112]
- What is the recommended way of dealing with max session duration of 24 hours for  websocket streams?
- Is it the correct way to close BinanceApiWebSocketClient and create a new one every 24 hours?
- Are there plans to perform reconnecting automatically by the client, behind the scenes (and restoring all subscribed channels)?

**Comment by ig-dev** [comment]
Does this answer your question? -> #81

**Comment by joaopsilva** [comment]
This has since been fixed in https://github.com/binance-exchange/binance-java-api/pull/133.

**Comment by denis-itskovich** [comment]
> This has since been fixed in #133.

As far as I understand, #133 refers to the keeping session alive when idle. My question was related to this:

> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark

 [Quoted from Binance official API doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md)

Can you reopen this issue, please?

**Comment by hp8wvvvgnj6asjm7** [comment]
lol how come nobody understood the question?

**Comment by Alihasnat10** [comment]
Did anyone find the answer to this query? Binance web socket connection is only valid for 24 hours. Is there any way to reconnect after 24 hours?

**Comment by jorinator** [comment]
Can this issue be reopened? It seems like there still isn't a solution after 4 years.

**Comment by Alihasnat10** [comment]
I solved this issue by setting a counter that counted the time of opening the socket. I close the socket at the 23rd hour and restart it. It is working perfectly fine.

**Comment by lokakshi** [comment]
@Alihasnat10 Could you pls share code reference for :How to deal with WebSocket stream.binance.com session duration limit (24h)

**Comment by Alihasnat10** [comment]
I have lost the code. Follow these steps:
1. Note the time when binance socket is created.
2. If the time is greater than 23 hours:
      a. Close the web socket
      b. Start the web socket again

**Comment by lokakshi** [comment]
@Alihasnat10 thanks !
